# Generated by Django 2.0.9 on 2018-12-28 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20181228_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mensaje',
            new_name='Post',
        ),
    ]
