# Generated by Django 2.0.9 on 2018-12-28 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20181228_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Mensaje',
        ),
    ]
